# Generated by Django 3.2.4 on 2021-07-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('dog_name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=25)),
                ('bread', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='appointments')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointment',
            },
        ),
    ]
