# Generated by Django 3.2.4 on 2021-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blogs')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
