# Generated by Django 3.2.4 on 2021-07-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='bread',
            new_name='breed',
        ),
    ]
